# Generated by Django 2.2.1 on 2019-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_id', models.IntegerField()),
                ('github_id', models.IntegerField()),
            ],
        ),
    ]
